### ISSUE TITLE
Switch away from Travis CI

### ISSUE THREAD

**Issue by Vindaar** [Vindaar/shell#14]
Since travis CI is now broken for open source projects, we need to switch away from it.

Possibly use Github Actions or Azure?

**Comment by disruptek** [comment]
@alaviss has built a great GitHub Actions CI that I use in all my recent stuff.  You can copy his `.github` from his dnsstamps project or use one from any of my badged projects, which vary only slightly.  His Action uses current Nim release binaries -- it's great stuff!

**Comment by Vindaar** [comment]
Damn, thanks a lot for that hint! I was procrastinating on it simply because I didn't want to spend the time writing my own config, haha.

**Comment by Vindaar** [comment]
Ok, done. Thanks again @disruptek!
