### ISSUE TITLE
Let me interact with y/n questions

### ISSUE THREAD

**Issue by ShalokShalom** [Vindaar/shell#20]
A script that I like to run does ask the user if he likes agree on something or not. 

It asks a simple yes/no prompt, as we have seen it multiple times. 

How to interact with such an instance?

I like to automate that in my program and could currently use only a hand-rolled implementation based on startProcess and manually reading the output and ... you get it. 

Do you see any alternative with `shell`?

**Comment by Vindaar** [comment]
(Sorry, I missed the issue)

Well, at some point I wanted to extend `shell` to include some functionality like the unix `expect` (https://linux.die.net/man/1/expect), but didn't get around to it. 

So at the moment `shell` won't be any help with these kind of situations (indeed, it can be really annoying running commands that require user input, as your program using `shell` will just halt).

I'd still like to be able to deal with such situations, if only in the beginning via a simple `seq[string]` argument to `shell`, which will be written to the process in order for any input needed or something like that.

**Comment by ShalokShalom** [comment]
How could you do that?

**Comment by Vindaar** [comment]
Well, either in the same way as `expect` does it (I imagine), i.e. you also give the expected string and then in code I would just check if the process wrote that string, and if so, send the desired command to the stdin of the process. 

Or else, without any expected inputs, play some games with input / output stream and send the commands to input based on some logic that I need to think about (if the process just reads a single line from stdin for each expected input, it would already be enough to just dump all inputs immediately split by newline after the process is started).

Does that answer your question?

**Comment by ShalokShalom** [comment]
I will leave that open, to track the issue. 👍🏼

**Comment by ShalokShalom** [comment]
Yuhuu, thanks!
