### ISSUE TITLE
Send without expections ;)

### ISSUE THREAD

**Issue by ShalokShalom** [Vindaar/shell#22]
Is it possible to `send:` a value, regardless of the expected line?

In a lot of scenarios, I would like to send the same value in any case, and it seems superfluous to provide any expectation.

So like: 
```
shell:
  ./nspawn.sh
  send: y
```

**Comment by Vindaar** [comment]
I guess currently not. It should be straightforward to add. Feel free to check out the code if you want!
I'll have a short look tomorrow morning!

Frohe Weihnachten! 🎄

**Comment by Vindaar** [comment]
Closed by #23, new version is tagged.
